version: "3.7"

services:
  comment-service-api-server:
    build:
      context: ./comment-api-server
      dockerfile: Dockerfile
    volumes:
      - ./comment-api-server/src:/app/src
    ports:
      - 9020-9029:8000
    env_file:
      - .env
    restart: unless-stopped

  comment-service-mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
      MONGO_DATABASE: "$MONGO_DATABASE"
      MONGO_USERNAME: "$MONGO_USERNAME"
      MONGO_PASSWORD: "$MONGO_PASSWORD"
    env_file:
      - .env
    expose:
      - 27017
    volumes:
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped
