version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: cooking_gateway
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./site-content:/usr/share/nginx/html
    ports:
      - 8081:80
      # - 443:443
      
