version: "3.7"

services:
  api:
    build: .
    restart: on-failure:5 
    ports: 
      - 8090-8099:${RECIPES_API_PORT}
    environment:
      MONGO_DATABASE: "${MONGO_DATABASE}"
      MONGO_PORT: "${MONGO_PORT}"
      RECIPES_API_PORT: "${RECIPES_API_PORT}"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongosetup
  mongo1:
    hostname: mongo1
    image: mongo:latest
    expose:
      - 27017
    restart: always
    volumes:
      - mongo1:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "recipe_replica" ]
  mongo2:
    hostname: mongo2
    image: mongo:latest
    expose:
      - 27017
    restart: always
    volumes:
      - mongo2:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "recipe_replica" ]
  mongo3:
    hostname: mongo3
    image: mongo:latest
    expose:
      - 27017
    restart: always
    volumes:
      - mongo3:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "recipe_replica" ]
  mongosetup:
    image: mongo:latest
    links:
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongo_setup.sh:/scripts/mongo_setup.sh:ro
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]

volumes:
  mongo1:
  mongo2:
  mongo3: