version: "3.7"

services:
  mongodb:
    image: mongo:latest
    restart: on-failure:5 
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DATABASE: "${MONGO_DATABASE}"
      MONGO_INITDB_USERNAME: "${MONGO_INITDB_USERNAME}"
      MONGO_INITDB_PASSWORD: "${MONGO_INITDB_PASSWORD}"
    ports:
      - 28090:27017
    volumes:
      - mongodata:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  api:
    build: .
    restart: on-failure:5 
    ports: 
      - 8090-8099:${RECIPES_API_PORT}
    environment:
      MONGO_DATABASE: "${MONGO_DATABASE}"
      MONGO_INITDB_USERNAME: "${MONGO_INITDB_USERNAME}"
      MONGO_INITDB_PASSWORD: "${MONGO_INITDB_PASSWORD}"
      MONGO_PORT: "${MONGO_PORT}"
      RECIPES_API_PORT: "${RECIPES_API_PORT}"
volumes:
  mongodata:
